### ISSUE TITLE
How does a lambda function assumes role while using python-lambda-local

### ISSUE THREAD

**Issue by shbhmbnsl1** [HDE/python-lambda-local#48]
I have created a lambda function in my local machine and testing it by running python-lambda-local command. 
This lambda function calls dynamoDB using boto3 to put some item in a table.
When testing the lambda function using python-lambda-local, it successfully puts the item in dynamoDB. 
My question is how this lambda function gets the access to dynamoDB even when I have not specified any role yet and still it works and puts the object to dynamoDB?

Sorry that I have to create this question as an issue, but I didn't find anything related on the web.

**Comment by freedomofkeima** [comment]
Do you have `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` set in your environment variables? Without implicitly specifying those keys to `boto3`, it will still work since `boto3` have multiple ways of retrieving AWS credentials.

```
The order in which Boto3 searches for credentials is:

1. Passing credentials as parameters in the boto.client() method
2. Passing credentials as parameters when creating a Session object
3. Environment variables
4. Shared credential file (~/.aws/credentials)
5. AWS config file (~/.aws/config)
6. Assume Role provider
7. Boto2 config file (/etc/boto.cfg and ~/.boto)
8. Instance metadata service on an Amazon EC2 instance that has an IAM role configured
```

Ref:
- https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuring-credentials
